# Criando nosso arquivo de workflow
name: Meu Primeiro Workflow
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Job de build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Utilizando action do github
        run: echo "Cheguei! Cheguei Brasil!"